// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QDD_nApALoU-m6EmapFKQDrqDuxyF7c',
    appId: '1:1082652549669:web:6c57fc031133a66db755cc',
    messagingSenderId: '1082652549669',
    projectId: 'close-contact-d88ba',
    authDomain: 'close-contact-d88ba.firebaseapp.com',
    storageBucket: 'close-contact-d88ba.appspot.com',
    measurementId: 'G-8S5Z53Q4D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmARF0c5dvxxaftp-O2iVJ6wGt88fnjFM',
    appId: '1:1082652549669:android:a5df820190ed4db2b755cc',
    messagingSenderId: '1082652549669',
    projectId: 'close-contact-d88ba',
    storageBucket: 'close-contact-d88ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv1uRFmGXttbwjw-p5wU9KQUypThdB29o',
    appId: '1:1082652549669:ios:4214a7efb3abd842b755cc',
    messagingSenderId: '1082652549669',
    projectId: 'close-contact-d88ba',
    storageBucket: 'close-contact-d88ba.appspot.com',
    iosClientId: '1082652549669-acivko6psd62jmtllmj0deq4j0l6e801.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv1uRFmGXttbwjw-p5wU9KQUypThdB29o',
    appId: '1:1082652549669:ios:4214a7efb3abd842b755cc',
    messagingSenderId: '1082652549669',
    projectId: 'close-contact-d88ba',
    storageBucket: 'close-contact-d88ba.appspot.com',
    iosClientId: '1082652549669-acivko6psd62jmtllmj0deq4j0l6e801.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );
}
